version: 0.2

env:
  variables:
    NODE_VERSION: '20'
    REGION: 'ap-northeast-2'
    PROD_BUILD_CMD: 'npm run tauri:build-prog'
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: $NODE_VERSION
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Checking Node.js and npm versions"
      - node -v
      - npm -v
  build:
    commands:
      - echo "Starting Tauri build..."
      - if [[ "$BUILD_ENV" == "prod" ]]; then $PROD_BUILD_CMD; fi
  post_build:
    commands:
      - echo "Build completed! Listing output files..."
      - ls -al src-tauri/target/release/bundle/msi/
      - ls -al src-tauri/target/release/bundle/dmg/

artifacts:
  files:
    - src-tauri/target/release/bundle/msi/haix-alarm-*_x64_en-US.msi
    - src-tauri/target/release/bundle/dmg/haix-alarm-*_x64.dmg
  discard-paths: yes
