version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - dnf update -y
      - dnf install -y libsoup3-devel --enablerepo=epel
      - dnf install -y --allowerasing curl gcc-c++ file git libX11-devel libXcursor-devel libXrandr-devel libXext-devel libXrender-devel alsa-lib-devel at-spi2-core-devel gtk3-devel glib2-devel pango-devel cairo-devel dbus-devel
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - source $HOME/.cargo/env
      - npm install -g env-cmd

  pre_build:
    commands:
      - npm install
      - rustup target add x86_64-unknown-linux-gnu
      - rustup show
      - export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/share/pkgconfig

  build:
    commands:
      - echo "Starting Dankkume Desktop Build"
      - npm run build:stg
      - npm run tauri:build-stg
      - npm run build:prod
      - npm run tauri:build-prod

  post_build:
    commands:
      - echo "Uploading MSI and DMG files to S3"
      - aws s3 cp src-tauri/target/release/bundle/msi/*.msi s3://stg-desktop-app/msi/ --acl public-read
      - aws s3 cp src-tauri/target/release/bundle/dmg/*.dmg s3://stg-desktop-app/dmg/ --acl public-read
#      - aws s3 cp src-tauri/target/release/bundle/msi/*.msi s3://YOUR_S3_BUCKET/haix-alarm/prod/ --acl public-read
#      - aws s3 cp src-tauri/target/release/bundle/dmg/*.dmg s3://YOUR_S3_BUCKET/haix-alarm/prod/ --acl public-read

artifacts:
  files:
    - src-tauri/target/release/bundle/msi/*.msi
    - src-tauri/target/release/bundle/dmg/*.dmg
  discard-paths: no
